[mode]
  # Set the value specifying from where user want to download model
  source="http-server"
[http-server]
  # URL path from where model file can be accessed
  base-url="http://9.114.99.184"
  # Name of the file(tar.gz) which would be present in http server
  file-name="models--ibm-granite--granite-3.2-8b-instruct.tar.gz"
  # Download path for the model inside the partition
  download-path="/var/huggingface"
