ARG BASE_UBI_IMAGE_TAG=9.5-1742914212
FROM registry.access.redhat.com/ubi9/ubi-minimal:${BASE_UBI_IMAGE_TAG} as hmc_builder

ARG PYTHON_VERSION=3.12

ENV VIRTUAL_ENV=/opt/venv
ENV PATH=${VIRTUAL_ENV}/bin:$PATH

WORKDIR /download_manager

RUN microdnf install -y dnf && dnf install -y \
    python${PYTHON_VERSION} python${PYTHON_VERSION}-pip vim \
    && dnf clean all \
    && python${PYTHON_VERSION} -m venv ${VIRTUAL_ENV} \
    && python -m pip install -U pip uv

COPY pyproject.toml download_vllm.py config.ini ./

RUN source ${VIRTUAL_ENV}/bin/activate && \
    /opt/venv/bin/pip3.12 install .

ENTRYPOINT [ "python3", "download_vllm.py"]
